title: i am curns
author: Jon Curnow
github_username: curns
header_pages:
  - about.md
plugins:
  - jekyll-relative-links
# theme: minima
remote_theme: jekyll/minima
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
